calib:
  num_samples: 128
  seq_length: 512
  min_seq_length: 0
  max_seq_length: 512
quant:
  wgts:
    static: true
    dtype: zint4
    group_shapes:
    - - 1
      - 128
    group_scale_dtypes:
    - torch.float16
    enable_calib_range: true
    calib_range:
      objective: ProductsError
      strategy: GridSearch
      granularity: Group
      degree: 2
      element_batch_size: 64
      sample_batch_size: -1
      element_size: 512
      sample_size: -1
      max_shrink: 0.8
      max_expand: 1.0
      num_grids: 20
      skip_proj_qkv: true
  ipts:
    static: false
    dtype: null
    group_shapes:
    - - 1
      - -1
    group_scale_dtypes:
    - torch.float16
  opts:
    static: false
    dtype: null
    group_shapes:
    - - 1
      - -1
    group_scale_dtypes:
    - torch.float16
  enable_smooth: true
  smooth:
    enable_xw: true
    xw:
      objective: OutputsError
      strategy: GridSearch
      granularity: Layer
      ranges:
      - - AbsMax
        - AbsMax
      alpha: 0.5
      beta: 0
      num_grids: 20
      skip_proj_qkv: false
      skip_proj_out: false
      skip_proj_1st: false
      skip_proj_2nd: false
    enable_yx: false