calib:
  num_samples: 128
  seq_length: 2048
  min_seq_length: 2048
  max_seq_length: 0
quant:
  wgts:
    static: true
    dtype: zint4
    group_shapes:
    - - 1
      - 128
    group_scale_dtypes:
    - torch.float16
    compute_dtype: null
    enable_calib_kernel: true
    calib_kernel:
      enable_gptq: true
      gptq:
        damp_percentage: 0.01
        block_size: 128
        num_inv_tries: 250
        hessian_block_size: 512
        include_proj_qkv: true
        include_proj_out: true
        include_proj_1st: true
        include_proj_2nd: true
    enable_calib_range: true
    calib_range:
      objective: TensorError
      strategy: GridSearch
      granularity: Group
      degree: 2.4
      element_batch_size: -1
      sample_batch_size: -1
      element_size: -1
      sample_size: -1
      pre_reshape: true
      outputs_device: cpu
      allow_kernel_calib: false
      max_shrink: 0.2
      max_expand: 1.0
      num_grids: 100
  ipts:
    static: false
    dtype: null
    group_shapes:
    - - 1
      - -1
    group_scale_dtypes:
    - torch.float16
    compute_dtype: null
  opts:
    static: false
    dtype: null
    group_shapes:
    - - 1
      - -1
    group_scale_dtypes:
    - torch.float16
    compute_dtype: null