JOB_SERVICE: Adapt
CUSTOM_DATASET_PATH : "custom_data/iccv09Data" 


MODEL : 'segnext' 
MODEL_PATH :  'segnext_mscan-t_1xb16-adamw-160k_ade20k-512x512'  # config of model in case of mmseg
CACHE_BOOL : False
LOCAL_MODEL_PATH: #This is empty becasue we are using the pretrained model from the internet. 


SEED : 56
DO_TRAIN : True
DO_EVAL : False
NUM_WORKERS : 4
BATCH_SIZE : 1
EPOCHS : 1
STEPS : 
OPTIMIZER : 'AdamW' 
LR : 5e-4
SCHEDULER_TYPE : 'MultiStepLR'
WEIGHT_DECAY : 0.0
BETA1 : 0.9
BETA2 : 0.999
ADAM_EPS : 1e-8 
INTERVAL : 'steps'
INTERVAL_STEPS : 4      #For interval based training loops in mmlabs 
NO_OF_CHECKPOINTS : 5
FP16 : False
RESUME_FROM_CHECKPOINT : False 
GRADIENT_ACCUMULATION_STEPS : 3
GRADIENT_CHECKPOINTING : False
BEGIN: 0
END: 50

#MMSEG SPECIFIC ARGUMENTS
amp :  False
resume  : #False # ['auto']
auto_scale_lr :  False
cfg_options  : None
launcher :  none
dest_root : './.mmdet_cache'   #This saves the checkpoints and .py files for the model configs and mmdet logs   
train_ann_file : "train_ann_file.txt" 
val_ann_file : "val_ann_file.txt" 
work_dir : ./results/mmdet  # same as output dir
checkpoint_interval : 45
train_img_file: images  #For MMSEG - Folder containing training images
train_seg_file: seg_maps  #For MMSEG - Folder containing training segmentation maps
val_img_file: images   #For MMSEG - Folder containing validation images
val_seg_file: seg_maps     #For MMSEG - Folder containing validation segmentation maps
num_classes: 8
class_list: ['sky', 'tree', 'road', 'grass', 'water', 'bldg', 'mntn', 'fg obj'] #List containing all class names
palette: [[128, 128, 128], [129, 127, 38], [120, 69, 125], [53, 125, 34], 
           [0, 11, 123], [118, 20, 12], [122, 81, 25], [241, 134, 51]]   #List of lists contaning class colors - [[r,g,b],[r,g,b],[r,g,b]]


LAST_LAYER_TUNING : True
FULL_FINE_TUNING : False

PEFT_METHOD : 'SSF'
peft_type : 'SSF'


Library :  'MMSEG'
cuda_id : '0'
OUTPUT_DIR : "/user_data/jobs/Adapt/IMGSEG"
OVERWRITE_OUTPUT_DIR : False
LOGGING_PATH : "/user_data/logs/Adapt/IMGSEG" 
MERGE_ADAPTER: False
TASK : 'image_segmentation'
auto_select_modules: True
SAVE_METHOD : 'state_dict'