#DATASET_ARGS :
JOB_SERVICE: Adapt
TRAIN_DIR : 'train/'
VAL_DIR : 'validation/'
CUSTOM_DATASET_PATH : "custom_data/face_det"  

#MODEL_ARGS :
MODEL : 'rtmdet'
MODEL_PATH :  'rtmdet_tiny_8xb32-300e_coco'  # config of model in case of mmdet
MODEL_VERSION : '1.0'
CACHE_BOOL : False
LOCAL_MODEL_PATH: 

#TRAINING_ARGS :
SEED : 56
DO_TRAIN : True
DO_EVAL : True
NUM_WORKERS : 4
BATCH_SIZE : 1
EPOCHS : 1
STEPS : 
OPTIMIZER : 'SGD' 
LR : 5e-3 
SCHEDULER_TYPE : 'CosineAnnealingLR'
WEIGHT_DECAY : 0.0
BETA1 : 0.9
BETA2 : 0.999
ADAM_EPS : 1e-8 
INTERVAL : 'steps'
INTERVAL_STEPS : 4
NO_OF_CHECKPOINTS : 5
FP16 : False
RESUME_FROM_CHECKPOINT : 
GRADIENT_ACCUMULATION_STEPS : 4
GRADIENT_CHECKPOINTING : False
BEGIN: 0
END: 50
WARMUP: 
T_MAX : 
MILESTONES : 
WARMUP_RATIO:
WARMUP_ITERS: 

#MMLABS_ARGS :
amp :  False
resume  : False # ['auto']
auto_scale_lr :  False
cfg_options  : None
launcher :  none
dest_root : './.mmdet_cache'       
train_ann_file : 'annotations.coco.json'      #mmdet - json file in coco format, mmseg- txt file containing fie names (voc format)
val_ann_file : 'annotations.coco.json'          #mmdet - json file in coco format, mmseg- txt file containing fie names (voc format)
work_dir : ./results/mmdet  # same as output dir
checkpoint_interval : 5
train_img_file:   #For MMSEG - Folder containing training images
train_seg_file:   #For MMSEG - Folder containing training segmentation maps
val_img_file:     #For MMSEG - Folder containing validation images
val_seg_file:     #For MMSEG - Folder containing validation segmentation maps
  
#FINE_TUNING_ARGS :
LAST_LAYER_TUNING : True
FULL_FINE_TUNING :  False



PEFT_METHOD : "LoRA"

#LoRA_CONFIG :
r : 32
alpha : 16
dropout : 0.1
peft_type : 'LoRA'
target_modules : 
fan_in_fan_out : False
init_lora_weights : True  

TASK : 'object_detection'
Library :  'MMDET' 
cuda_id : '0,1'
OUTPUT_DIR : "/user_data/jobs/Aadpt/OBJDET"
OVERWRITE_OUTPUT_DIR : False
LOGGING_PATH : "/user_data/logs/Adapt/OBJDET"
dataset_text_field: "image"
MERGE_ADAPTER: False
auto_select_modules: True
SAVE_METHOD : 'state_dict'

#DDP ARGS
DDP: True
num_nodes: 1
FSDP: False